/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadodetodosa;

import java.util.ArrayList;
import java.util.TreeSet;

/**
 *
 * @author nahue
 */
public class JFMenuGeneral extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public JFMenuGeneral() {
        initComponents();
        this.setTitle("Menú general");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmiAdministracion = new javax.swing.JMenu();
        jmiAdminProductos = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsRubro = new javax.swing.JMenuItem();
        jmiConsNombre = new javax.swing.JMenuItem();
        jmiConsPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        jmiAdministracion.setText("Administración");
        jmiAdministracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmiAdminProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmiAdminProductos.setText("Productos");
        jmiAdminProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdminProductosActionPerformed(evt);
            }
        });
        jmiAdministracion.add(jmiAdminProductos);

        jMenuBar1.add(jmiAdministracion);

        jmConsultas.setText("Consultas");
        jmConsultas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jmiConsRubro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmiConsRubro.setText("Por Rubro");
        jmiConsRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsRubro);

        jmiConsNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmiConsNombre.setText("Por Nombre");
        jmiConsNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsNombre);

        jmiConsPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jmiConsPrecio.setText("Por Precio");
        jmiConsPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsPrecio);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAdminProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdminProductosActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        JIFGestionProductos gp = new JIFGestionProductos();
        gp.setVisible(true);
        gp.setTitle("Administrar productos");
        jdpEscritorio.add(gp);
        jdpEscritorio.moveToFront(gp);        
    }//GEN-LAST:event_jmiAdminProductosActionPerformed

    private void jmiConsRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsRubroActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        JIFConsPorRubro cpr = new JIFConsPorRubro();
        cpr.setVisible(true);
        cpr.setTitle("Consulta por rubro");
        jdpEscritorio.add(cpr);
        jdpEscritorio.moveToFront(cpr);
    }//GEN-LAST:event_jmiConsRubroActionPerformed

    private void jmiConsNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsNombreActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        JIFConsPorNombre cpn = new JIFConsPorNombre();
        cpn.setVisible(true);
        cpn.setTitle("Consulta por nombre");
        jdpEscritorio.add(cpn);
        jdpEscritorio.moveToFront(cpn);
    }//GEN-LAST:event_jmiConsNombreActionPerformed

    private void jmiConsPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsPrecioActionPerformed
        jdpEscritorio.removeAll();
        jdpEscritorio.repaint();
        JIFConsPorPrecio cpp = new JIFConsPorPrecio();
        cpp.setVisible(true);
        cpp.setTitle("Consulta por precio");
        jdpEscritorio.add(cpp);
        jdpEscritorio.moveToFront(cpp);
    }//GEN-LAST:event_jmiConsPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuGeneral().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmiAdminProductos;
    private javax.swing.JMenu jmiAdministracion;
    private javax.swing.JMenuItem jmiConsNombre;
    private javax.swing.JMenuItem jmiConsPrecio;
    private javax.swing.JMenuItem jmiConsRubro;
    // End of variables declaration//GEN-END:variables
    public static TreeSet<Producto> tsProductos = new TreeSet<>(Ordenamientos.porCodigo);    
    public static ArrayList<Producto> alProdNombre = new ArrayList<>(); // para que la consulta por nombre muestre productos en la tabla ordenados por orden alfabético    
    public static ArrayList<Producto> alProdPrecio = new ArrayList<>(); // para que la consulta por nombre muestre productos en la tabla ordenados por orden crecientes    

    // métodos extra
//    private void cargarElementos(TreeSet<Producto> ts){              
//        ts.add(new Producto(7, "aproducto7", 756, 700, Rubro.PERFUMERÍA));
//        ts.add(new Producto(8, "aabproducto8", 70, 800, Rubro.PERFUMERÍA));
//        ts.add(new Producto(9, "aAbproducto9", 704, 900, Rubro.PERFUMERÍA));
//        ts.add(new Producto(3, "bccproducto3", 760, 300, Rubro.COMESTIBLE));
//        ts.add(new Producto(4, "aBproducto4", 40, 400, Rubro.LIMPIEZA));
//        ts.add(new Producto(5, "bCproducto5", 50, 500, Rubro.LIMPIEZA));
//        ts.add(new Producto(6, "cproducto6", 50, 600, Rubro.LIMPIEZA));
//        ts.add(new Producto(1, "aproducto1", 10, 100, Rubro.COMESTIBLE));
//        ts.add(new Producto(2, "bproducto2", 20, 200, Rubro.COMESTIBLE));              
//    }
//    
//    private void cargarElementos(ArrayList<Producto> al){              
//        al.add(new Producto(7, "aproducto7", 756, 700, Rubro.PERFUMERÍA));
//        al.add(new Producto(8, "aabproducto8", 70, 800, Rubro.PERFUMERÍA));
//        al.add(new Producto(9, "aAbproducto9", 704, 900, Rubro.PERFUMERÍA));
//        al.add(new Producto(3, "bccproducto3", 760, 300, Rubro.COMESTIBLE));
//        al.add(new Producto(4, "aBproducto4", 40, 400, Rubro.LIMPIEZA));
//        al.add(new Producto(5, "bCproducto5", 50, 500, Rubro.LIMPIEZA));
//        al.add(new Producto(6, "cproducto6", 50, 600, Rubro.LIMPIEZA));
//        al.add(new Producto(1, "aproducto1", 10, 100, Rubro.COMESTIBLE));
//        al.add(new Producto(2, "bproducto2", 20, 200, Rubro.COMESTIBLE));              
//    }
}
