/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadodetodosa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nahue
 */
public class JIFConsPorRubro extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFConsPorRubro
     */
    public JIFConsPorRubro() {
        initComponents();
        armarCabecera();
        armarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitConsProd = new javax.swing.JLabel();
        jlSeleccionarRubro = new javax.swing.JLabel();
        jcbRubro = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jlListaProductos = new javax.swing.JLabel();

        setClosable(true);

        jlTitConsProd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTitConsProd.setText("Consulta de productos por rubro");

        jlSeleccionarRubro.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlSeleccionarRubro.setText("Seleccione el rubro:");

        jcbRubro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcbRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRubroActionPerformed(evt);
            }
        });

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtProductos);

        jlListaProductos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlListaProductos.setText("Lista de productos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlSeleccionarRubro)
                                .addGap(35, 35, 35)
                                .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlListaProductos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jlTitConsProd)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitConsProd)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSeleccionarRubro)
                    .addComponent(jcbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jlListaProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRubroActionPerformed
        borrarFilas();
        mostrarProductos();
    }//GEN-LAST:event_jcbRubroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Rubro> jcbRubro;
    private javax.swing.JLabel jlListaProductos;
    private javax.swing.JLabel jlSeleccionarRubro;
    private javax.swing.JLabel jlTitConsProd;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    // métodos extra
    private void armarCabecera() {
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtProductos.setModel(modelo);
    }

    private void mostrarProductos() {
        for (Producto prod : JFMenuGeneral.tsProductos) {
            if (prod.getRubro() == jcbRubro.getSelectedItem()) {
                modelo.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getStock()});
            }
        }
    }

    private void armarComboBox() {
        jcbRubro.addItem(Rubro.COMESTIBLE);
        jcbRubro.addItem(Rubro.LIMPIEZA);
        jcbRubro.addItem(Rubro.PERFUMERÍA);
    }
    
    private void borrarFilas(){
        int indFil=jtProductos.getRowCount()-1;
        for (;indFil >=0;indFil--) {
            modelo.removeRow(indFil);
        }
    }
}
