/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mercadodetodosa;

import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nahue
 */
public class JIFConsPorNombre extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFConsPorNombre
     */
    public JIFConsPorNombre() {
        initComponents();
        armarCabecera();
        JFMenuGeneral.alProdNombre.addAll(JFMenuGeneral.tsProductos);
        Collections.sort(JFMenuGeneral.alProdNombre, Ordenamientos.porNombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlIngDes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jlTitConsProd = new javax.swing.JLabel();
        jlListaProductos = new javax.swing.JLabel();
        jtfDescripcion = new javax.swing.JTextField();
        jlAdverLista = new javax.swing.JLabel();

        setClosable(true);

        jlIngDes.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlIngDes.setText("Ingrese la descripción:");

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtProductos);

        jlTitConsProd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTitConsProd.setText("Consulta de productos por nombre");

        jlListaProductos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlListaProductos.setText("Lista de productos");

        jtfDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfDescripcionKeyReleased(evt);
            }
        });

        jlAdverLista.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlIngDes)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlListaProductos)
                            .addComponent(jlAdverLista, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jlTitConsProd)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitConsProd)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIngDes)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jlListaProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAdverLista, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDescripcionKeyReleased
        borrarFilas();
        mostrarProductos();
    }//GEN-LAST:event_jtfDescripcionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlAdverLista;
    private javax.swing.JLabel jlIngDes;
    private javax.swing.JLabel jlListaProductos;
    private javax.swing.JLabel jlTitConsProd;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTextField jtfDescripcion;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }

    };

    // métodos extra
    private void armarCabecera() {
        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jtProductos.setModel(modelo);
    }

    private void mostrarProductos() {
        for (Producto prod : JFMenuGeneral.alProdNombre) {
            if (prod.getDescripcion().toLowerCase().startsWith(jtfDescripcion.getText().toLowerCase())) {
                modelo.addRow(new Object[]{prod.getCodigo(), prod.getDescripcion(), prod.getPrecio(), prod.getStock()});
            }
        }
        if (jtProductos.getRowCount() == 0) {
            jlAdverLista.setText("No se han encontrado productos cuyo nombre empiece así.");
        } else {
            jlAdverLista.setText("");
        }
    }

    private void borrarFilas() {
        int indFil = jtProductos.getRowCount() - 1;
        for (; indFil >= 0; indFil--) {
            modelo.removeRow(indFil);
        }
    }
}
